### ISSUE TITLE
Need Some Information ?

### ISSUE THREAD

**Issue by TerraceFe** [araafroyall/Cleaner-Pro-Lite#11]
Why even publish it on GitHub if there's not a single line of code? He even commits the .apk file to source control🤣 

Dude was publishing his little Trojan app onto GitHub trying to pass off as a open source project lol

**Comment by araafroyall** [comment]
Stop spreading voilance here. 
Currently i am working on update v2.9

Source Code will be available within 2 days 
wait or find better app 👍

**Comment by TerraceFe** [comment]
> Source Code will be available within 2 days
That's what you said a week ago, where's your source code huh? 🤣

Trojan app confirmed

**Comment by araafroyall** [comment]
Source code is now available 👍
