### ISSUE TITLE
‎ 

### ISSUE THREAD

**Issue by Magisk-Modules** [araafroyall/Cleaner-Pro-Lite#27]
### Bug Submission

On Update option The github button open helper app  page not Cleaner main page

### Android Version

Any Android

### Comments or Extra Info

```cmt
Please fix as soon as possible
```

### App Version

v3.0

**Comment by araafroyall** [comment]
willl be fixed in v3.1 👍

**Comment by araafroyall** [comment]
Fixed 👍

```Fixed
Thanks for information
```
