### ISSUE TITLE
New UI Sample‎ 

### ISSUE THREAD

**Issue by araafroyall** [araafroyall/Cleaner-Pro-Lite#30]
### Explain Feature

```info
Sample of upcoming UI Update in v3.2
```

### Comment or Extra Info

![Screenshot_2024-01-04-19-13-22-039_com my newproject](https://github.com/araafroyall/Cleaner-Pro-Lite/assets/87515236/a26d3880-73b3-4d69-80dc-282d4a82e219)

**Comment by hiru12** [comment]
I like this new UI. Do you have a plan on releasing the app on Fdroid for more exposure?

**Comment by araafroyall** [comment]
> I like this new UI. Do you have a plan on releasing the app on Fdroid for more exposure?

Brother , UI & Theme work is completed , i will release new update soon within 5 days 👍

first i need to understand how to post in fdroid than i will surely do .

Also i will reduce premium price in next update so many users can support this small project 👍

**Comment by araafroyall** [comment]
@hiru12 Brother , UI & Theme work is completed , i will release new update soon within 5 days 👍 
 
first i need to understand how to post in fdroid than i will surely do . 
 
Also i will reduce premium price in next update so many users can support this small project 👍
